### ISSUE TITLE
Unknown issue with `Do`

### ISSUE THREAD

**Issue by IMax153** [ts-plus/typescript#208]
In the following test, the example with `Do` times out no matter how long I set the timeout to be. Rewriting the test to utilize `Effect.Do` allowed the test to pass in milliseconds.

I've left both versions in the file for reference: https://github.com/Effect-TS/core/blob/7159b2029995eb928c1945721ddeb2a4282c7d24/packages/core/_test/concurrent/ReentrantLock.test.ts#L70

cc @mikearnaldi @0x706b

**Comment by mikearnaldi** [comment]
The same code passes with TReentrantLock so it must have been a bug on the ReentrantLock implementation, also checking the compiled code it was correctly using map+flatMap in the correct order
