### ISSUE TITLE
Fluent type guards no longer work properly in `@tsplus/installer@0.0.129`

### ISSUE THREAD

**Issue by IMax153** [ts-plus/typescript#214]
After upgrading `@tsplus/installer` from `v0.0.128` to `v0.0.129`, I noticed that type guards are not working properly anymore. 

See below for an example from `@tsplus/stdlib`:

![image](https://user-images.githubusercontent.com/38051499/181495625-a14b9cc1-3b73-498b-b82e-f0f981c35c9d.png)

**Comment by mikearnaldi** [comment]
cc @0x706b

**Comment by mikearnaldi** [comment]
Repro:

```ts
import { Either } from "@tsplus/stdlib/data/Either"

declare const either: Either<string, number>

if (either.isLeft()) {
    const x: string = either.left
    console.log(x)
}


if (either.isRight()) {
    const x: number = either.right
    console.log(x)
}
```

![Screenshot 2022-08-04 102816](https://user-images.githubusercontent.com/24249610/182813648-9e10e8ad-31b6-41b9-8c01-b45bbd83e43b.png)
![Screenshot 2022-08-04 102845](https://user-images.githubusercontent.com/24249610/182813802-a18fbc2c-c697-48f2-ba84-a6a5e5741338.png)

**Comment by mikearnaldi** [comment]
seems to be due to type unification, if I remove unification it works

**Comment by mikearnaldi** [comment]
rebased with microsoft-main and added the repro

**Comment by mikearnaldi** [comment]
Should be fixed by https://github.com/ts-plus/typescript/pull/218 please @IMax153 give it a test to see if it breaks anything else

**Comment by IMax153** [comment]
@mikearnaldi - indeed #218 fixes this issue.
