### ISSUE TITLE
External declarations search modules from the type json file, instead of from the current project

### ISSUE THREAD

**Issue by patroza** [ts-plus/typescript#246]
When using pnpm with workspace, and the modules like @fp-ts/data are only available in a subpackage, but not in the root node_modules, then it seems like the `tsPlusPaths` must be relatively to the package directory, and not in the root of the repo.
aka from packages/bla, 
works
```json
        "tsPlusTypes": [
            "./vendor/fp-ts-data-tsplus.json"
        ],
```
fails:
```json
        "tsPlusTypes": [
            "../../vendor/fp-ts-data-tsplus.json"
        ],
```
this part ends up with `undefined` values: `const { resolvedModule } = resolveModuleName(moduleName, resolvedPath, options, sys);`

**Comment by 0x706b** [comment]
Possible fix, if you want to try it out, add this to your typescript resolution. I don't have a great environment set up to test this at the moment. I can get one set up later if needed:

`https://github.com/0x706b/typescript/raw/815e859542/typescript-5.0.0-tsplus.20221226.tgz`

**Comment by patroza** [comment]
@0x706b this seems to work well now, thanks!
