### ISSUE TITLE
External definitions with conflicting Type fluent and Type.Ops static definitions cause errors

### ISSUE THREAD

**Issue by patroza** [ts-plus/typescript#251]
E.g `@fp-ts/data/Option` 's isSome and isNone, you want to define them as fluent (not getter) because they type narrow, but you also want to define them as static on the 'virtual' Option.Ops.

This however leads to when using `Option.isSome` that it tries to resolve the fluent function and therefore fails.

Actually, it seems there are other issues with e.g interface ReadonlyArray marked as Companion object; ReadonlyArray.map etc exists and leads to the default implement on the prototype instead:
```ts
    /**
     * Calls a defined callback function on each element of an array, and returns an array that contains the results.
     * @param callbackfn A function that accepts up to three arguments. The map method calls the callbackfn function one time for each element in the array.
     * @param thisArg An object to which the this keyword can refer in the callbackfn function. If thisArg is omitted, undefined is used as the this value.
     */
    map<U>(callbackfn: (value: T, index: number, array: T[]) => U, thisArg?: any): U[];
```

<img width="463" alt="Screenshot 2022-12-27 at 16 35 28" src="https://user-images.githubusercontent.com/42661/209688471-c2ce424c-7b5c-4a47-badf-ec0f5a330d01.png">

**Comment by 0x706b** [comment]
This seems to work for me (using branch `pk/fixes`) after adding the definition to the JSON and restarting tsserver

<img width="953" alt="Screenshot 2022-12-27 at 11 35 49 AM" src="https://user-images.githubusercontent.com/20319430/209695141-4a758a6d-5944-4e0c-bd8d-aeb63a5afcc3.png">

**Comment by patroza** [comment]
@0x706b I can still reproduce this on the latest of https://github.com/effect-ts-app/libs/pull/21
when I change `packages/core/_src/Option.ts` line 37,  `function convert`, into:
```ts
function convert(a: any) {
  return Opt.isSome(a) || Opt.isNone(a) ? a : Opt.fromNullable(a)
}
```
I get `Expected 0 arguments, but got 1.ts(2554)`

**Comment by patroza** [comment]
hm, my bad, this actually seems to work when you put the right definitions into place 😊
