### ISSUE TITLE
Quick info `this` type should be instantiated

### ISSUE THREAD

**Issue by 0x706b** [ts-plus/typescript#26]
(leaving this issue so I remember later)

When viewing `quickInfo`, the name of a generic `this` type should preferably be the instantiated type, and not the generic.

![Screen Shot 2022-02-01 at 12 02 38 AM](https://user-images.githubusercontent.com/20319430/151915240-f26fb709-3bf5-4d43-b722-b8b15f00dd10.png)

**Comment by mikearnaldi** [comment]
also the same should be done on every call expression for every parameter, it is already the case with plain signature but it seems we are not doing something for the patched ones
