### ISSUE TITLE
Shadowing can overwrite global functions when arguments have the same name

### ISSUE THREAD

**Issue by IMax153** [ts-plus/typescript#62]
Take the following example:

```typescript
/**
 * Runs the specified effect on the specified runtime configuration, restoring
 * the old runtime configuration when it completes execution.
 *
 * @tsplus static ets/EffectOps withRuntimeConfig
 */
export function withRuntimeConfig<R, E, A>(
  runtimeConfig: LazyArg<RuntimeConfig>,
  effect: LazyArg<Effect<R, E, A>>,
  __etsTrace?: string
): Effect<R, E, A> {
  return Effect.runtimeConfig.flatMap((currentRuntimeConfig) =>
    Effect.acquireRelease(
      Effect.setRuntimeConfig(runtimeConfig) > Effect.yieldNow,
      effect,
      Effect.setRuntimeConfig(currentRuntimeConfig)
    )
  )
}
```

Because the `runtimeConfig` combinator is defined in the same file as `withRuntimeConfig`, after compilation `Effect.runtimeConfig` ends up referring to the argument of the same name instead of the global combinator. 

Check out the compiled version below:

```typescript
function withRuntimeConfig(runtimeConfig2, effect, __etsTrace) {
  // ======================^^^^^^^vvvvvvvvvv
  return tsplus_module_6.chain_(runtimeConfig2, (currentRuntimeConfig) => {
    return tsplus_module_5.acquireRelease(() => tsplus_module_4.zipRight_(setRuntimeConfig(runtimeConfig2), () => tsplus_module_3.yieldNow), effect, () => setRuntimeConfig(() => currentRuntimeConfig));
  });
}
```

**Comment by mikearnaldi** [comment]
@0x706b I know we kind of opted to add a diagnostic but couldn't we detect in the transformer if the identifier is shadowed and add a further statement to use an internal name?

like in the case above we could `createUniqueIdentifier("runtimeConfig")` and use that together with a `const newId = runtimeConfig` exactly on the next statement from where `runtimeConfig` is defined

**Comment by 0x706b** [comment]
I think we could in theory. At the moment, I have no idea how. The way I see it, the majority of the work will be in detecting that a case like this occurs. So, it seems to me that if we can detect that this kind of case occurs in the checker to show a diagnostic, then we might as well go the extra step and add a transformation for it.

**Comment by 0x706b** [comment]
Or, we could make it easy and bypass the detection altogether. Just make the unique identifier by default and use it for all transformations of that extension in the same file.

**Comment by mikearnaldi** [comment]
Detecting the change should not be too problematic, it is a matter of getting the locals of the current body and check if there is an identifier named equally which should always be the case given the function/constant exists and get the definition, if the definition is equal to the one we want fine if it isn't it means it is shadowed.

BUT I also like the idea of making it the default to introduce a local name per each used function/constant that should be easy and it can still be optimized when tree-shaking
