### ISSUE TITLE
Don't show autocompletion for generic type, when the generic parameter is not matched

### ISSUE THREAD

**Issue by kasperpeulen** [ts-plus/typescript#63]
Consider this code:

```ts
declare global {
  /** @tsplus type Array */
  export interface Array<T> {}
}

/**
 * @tsplus fluent Array sum
 */
export function sum(self: Array<number>): number {
  return self.reduce((prev, cur) => prev + cur, 0)
}

/**
 * @tsplus fluent Array average
 */
export function average(self: Array<number>): number {
  return self.sum() / self.length
}

const arrayOfObjects = [{ a: 1 }];

arrayOfObjects.^
```

The extension methods `sum` and `average` need a subtype of `Array<number>`, and so should not be in the list of autocompletions when the type is `Array<{a:1}>`:

<img width="441" alt="image" src="https://user-images.githubusercontent.com/1035299/155804396-c4e723be-5c6f-4822-af9d-6eb9f0bb024a.png">

**Comment by mikearnaldi** [comment]
This is expected, follows the same convention as instance methods:

![Screenshot 2022-03-17 144612](https://user-images.githubusercontent.com/24249610/158830176-bf5f8504-b095-42c2-9e6b-c7817f5c4906.png)
